server:
  port: 8082
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      batch-size: 10
      retries: 1
      acks: 1
      group-id: my-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      test: order-events